"""Added relationship between ChatSession and ChatMessage

Revision ID: 1a052c74e67e
Revises: cca362f79d49
Create Date: 2024-11-16 14:33:49.533063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a052c74e67e'
down_revision = 'cca362f79d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('context')

    # ### end Alembic commands ###
