"""Remove context field from ChatSession

Revision ID: cca362f79d49
Revises: b7c78380a3f3
Create Date: 2024-11-16 14:12:38.978270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca362f79d49'
down_revision = 'b7c78380a3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('context', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'context')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
